---
kind: pipeline
name: default

steps:
- name: build-hschain-utxo
  image: nixos/nix
  privileged: true
  network_mode: host
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - master
  cron:
    exclude:
    - nightly
