port      : 45003
seeds     :
    - "127.0.0.1:45004"
privKey   : "3Fj8bZjKc53F2a87sQaFkrDas2d9gjzK57FmQwnNnSHS"
validators:
    - "HVQNfbH8rj2uVb6XyC41wzGCMGVFooeBZJMLnRBJifTX"
    - "HUs35FXTSYA3zY39MrKjqFdeCvTxx97uccPFxvwpqgt7"
    - "AZ3m8VUkPJ8iGNgQ5zpG4rMBqg5VNAYtSaJDmrR4Rz1m"
    - "2PggMrWVjsvUvrZHqYVgH4PRpjVp2oYJe9gjaWrU1R4m"
      # dbName  : "/run/user/1000/db/node-3"
logs:
  files : []
  # - type      : "ScribeJSON"
  #    path      : "logs/node-3.log"
  #    severity  : "Debug"
  #    verbosity : "V2"
  namespace: "validator-node3"

