server:
      host: 127.0.0.1
      port: 8080
node:
  port:  45000
  seeds: []
  privKey   : "RP3gBEiGMcd2Ha1oCW2eHXUZrR7rkuEVjcSzwuStCmF"
  validators:
          - "9uri4uofrVFf8U7xAqeLBeLvrmKed7bmD488ZtxMv2Bh"
  # dbName  : "/run/user/1000/db/node-web"
  logs:
        files : []
        #  - type      : "ScribeJSON"
        #    severity  : "Debug"
        #    path      : "logs/node-web.log"
        #    verbosity : "V2"
        namespace: "node-web"
