port      : "45001"
seeds     :
        - "127.0.0.1:45002"
        - "127.0.0.1:45003"
        - "127.0.0.1:45004"
privKey   : "2K7bFuJXxKf5LqogvVRQjms2W26ZrjpvUjo5LdvPFa5Y"
validators:
        - "HVQNfbH8rj2uVb6XyC41wzGCMGVFooeBZJMLnRBJifTX"
        - "HUs35FXTSYA3zY39MrKjqFdeCvTxx97uccPFxvwpqgt7"
        - "AZ3m8VUkPJ8iGNgQ5zpG4rMBqg5VNAYtSaJDmrR4Rz1m"
        - "2PggMrWVjsvUvrZHqYVgH4PRpjVp2oYJe9gjaWrU1R4m"
dbName  : "db/node-1"
logs:
  files :
    - type      : "ScribeJSON"
      path      : "logs/node-1.log"
      severity  : "Debug"
      verbosity : "V2"
  namespace: "validator-node1"

