server:
      host: 127.0.0.1
      port: 8080
node:
  port: "45000"
  seeds:
          - "127.0.0.1:45001"
          - "127.0.0.1:45002"
          - "127.0.0.1:45003"
          - "127.0.0.1:45004"
  validators:
          - "HVQNfbH8rj2uVb6XyC41wzGCMGVFooeBZJMLnRBJifTX"
          - "HUs35FXTSYA3zY39MrKjqFdeCvTxx97uccPFxvwpqgt7"
          - "AZ3m8VUkPJ8iGNgQ5zpG4rMBqg5VNAYtSaJDmrR4Rz1m"
          - "2PggMrWVjsvUvrZHqYVgH4PRpjVp2oYJe9gjaWrU1R4m"
  dbName  : "db/node-web"
  logs:
        files :
          - type      : "ScribeJSON"
            severity  : "Debug"
            path      : "logs/node-web.log"
            verbosity : "V2"
        namespace: "node-web"
